BCCSP:
  Default: SW
  SW:
    Hash: SHA2
    Security: 256
    FileKeyStore:
      KeyStorePath: /etc/hyperledger/fabric/msp/keystore
NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.Hospital_A.example.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.Hospital_A.example.com-cert.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/ca.Hospital_A.example.com-cert.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/ca.Hospital_A.example.com-cert.pem
    OrganizationalUnitIdentifier: orderer
