peer:
  id: peer0.Hospital_A.example.com
  networkId: dev
  listenAddress: 0.0.0.0:7051
  address: 0.0.0.0:7051
  addressAutoDetect: false
  keepalive:
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s

  gossip:
    bootstrap: peer0.Hospital_A.example.com:7051
    useLeaderElection: true
    orgLeader: false
    membershipTrackerInterval: 5s
    maxBlockCountToStore: 100
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval:
    publishCertPeriod: 10s
    skipBlockVerification: false
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1500ms
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    maxConnectionAttempts: 120
    msgExpirationFactor: 20

  tls:
    enabled: true
    clientAuthRequired: false
    cert:
      file: tls/server.crt
    key:
      file: tls/server.key
    rootcert:
      file: tls/ca.crt
    clientRootCAs:
      files:
      - tls/ca.crt

  authentication:
    timewindow: 15m

  fileSystemPath: /var/hyperledger/production

  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
    PKCS11:
      Library:
      Label:
      Pin:
      Hash:
      Security:
      FileKeyStore:
        KeyStore:

  mspConfigPath: msp
  localMspId: Hospital_AMSP
  client:
    connTimeout: 3s

  deliveryclient:
    reconnectTotalTimeThreshold: 3600s
    connTimeout: 3s
    reConnectBackoffThreshold: 3600s

  localMspType: bccsp

  profile:
    enabled: false
    listenAddress: 0.0.0.0:6060

  adminService:
    listenAddress: 0.0.0.0:9443

  metrics:
    provider: prometheus
    statsd:
      network: udp
      address: 127.0.0.1:8125
      writeInterval: 10s
      prefix: server

  # Quantum-specific configurations
  quantum:
    enabled: true
    keyStore: /etc/hyperledger/fabric/quantum_keys
    keyTypes: ["Falcon", "Kyber"]

ledger:
  blockchain:
  state:
    stateDatabase: CouchDB
    couchDBConfig:
      couchDBAddress: couchdb:5984
      username: admin
      password: adminpw
      maxRetries: 3
      maxRetriesOnStartup: 12
      requestTimeout: 35s
      internalQueryLimit: 1000
      maxBatchUpdateSize: 1000
      warmIndexesAfterNBlocks: 1
      createGlobalChangesDB: false
      cacheSize: 64
  history:
    enableHistoryDatabase: true

operations:
  listenAddress: 0.0.0.0:9443
  tls:
    enabled: false
    cert:
      file:
    key:
      file:
    clientAuthRequired: false
    clientRootCAs:
      files: []

chaincode:
  install: true
  startuptimeout: 300s
  executetimeout: 30s
  logging:
    level: info

vm:
  endpoint: unix:///var/run/docker.sock
  docker:
    tls:
      enabled: false
    attachStdout: false